# Generated by Django 2.1.2 on 2018-10-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
    ]
