# Generated by Django 2.1.2 on 2018-10-13 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
